### ISSUE TITLE
Missing support for Linux arm64/aarch64 architecture

### ISSUE THREAD

**Issue by Xhoenix** [MobSF/yara-python-dex#2]
While installing `mobsf` in a Linux arm64/aarch64 machine the following error is shown:-

![image](https://github.com/MobSF/yara-python-dex/assets/86168235/fc21513f-f91c-4aa7-b9be-c4e68ab50271)

I checked pypi and there are currently no files for Linux arm64. I was able to successfully build `yara-python-dex` for aarch64 locally. It'd be nice to have arm64 support.

**Comment by Xhoenix** [comment]
@ajinabraham Can you look into this?

**Comment by ajinabraham** [comment]
We generate a lot of builds targeting different archs. https://pypi.org/project/yara-python-dex/#files
If a particular one is not found, you will have to build it locally.
